baseURL = "https://jmaargh.github.io/punter/"
languageCode = "en-gb"
title = "Punter"
publishDir = "../docs"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  themeColor = "purple"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 1
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.png"

[languages]
  [languages.en]
    languageName = "English"
    title = "Punter"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read more posts"

    [languages.en.params.logo]
      logoText = "Punter"
      logoHomeLink = "/punter"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
